# Generated by Django 5.2.17 on 2026-09-19 14:51

import django.core.validators
import django.db.models.deletion
import shops.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Dükkan adı')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=90, unique=True, verbose_name='Adres')),
                ('description', models.TextField(blank=True, max_length=600, validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Açıklama')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(default='Kocaeli', max_length=40, verbose_name='İl')),
                ('district', models.CharField(default='Karamürsel', max_length=40, verbose_name='İlçe')),
                ('neighborhood', models.CharField(blank=True, max_length=60, verbose_name='Mahalle')),
                ('address', models.CharField(max_length=255, verbose_name='Adres tarifi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('show_prices', models.BooleanField(default=True, verbose_name='Fiyatları göster')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(choices=[(15, '15 dakika'), (20, '20 dakika'), (30, '30 dakika')], default=30, verbose_name='Randevu saati aralığı')),
                ('booking_window_days', models.PositiveSmallIntegerField(choices=[(7, '7 gün'), (14, '14 gün'), (30, '30 gün')], default=14, verbose_name='Kaç gün ilerisine randevu alınabilir')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Dükkan',
                'verbose_name_plural': 'Dükkanlar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Hizmet adı')),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10, message='Süre en az 10 dakika olmalı.'), django.core.validators.MaxValueValidator(180, message='Süre en fazla 180 dakika olabilir.'), shops.models.validate_duration_step], verbose_name='Süre (dakika)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message="Fiyat 0'dan büyük olmalı. Bilmiyorsan boş bırak.")], verbose_name='Fiyat (₺)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shop', verbose_name='Dükkan')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Not')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='shops.shop', verbose_name='Dükkan')),
            ],
            options={
                'verbose_name': 'Kapalı gün',
                'verbose_name_plural': 'Kapalı günler',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'date'), name='uniq_shop_closure_date')],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('is_open', models.BooleanField(default=True, verbose_name='Açık')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Açılış')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Kapanış')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Mola başlangıcı')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Mola bitişi')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='shops.shop', verbose_name='Dükkan')),
            ],
            options={
                'verbose_name': 'Çalışma saati',
                'verbose_name_plural': 'Çalışma saatleri',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'weekday'), name='uniq_shop_weekday')],
            },
        ),
    ]
