# Generated by Django 5.2.17 on 2026-09-19 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=60, verbose_name='Hizmet adı')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fiyat (₺)')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('start_time', models.TimeField(verbose_name='Başlangıç')),
                ('end_time', models.TimeField(verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('completed', 'Tamamlandı'), ('no_show', 'Gelmedi'), ('cancelled', 'İptal edildi')], default='scheduled', max_length=10, verbose_name='Durum')),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Müşteri'), ('shop', 'Dükkan')], max_length=10, null=True, verbose_name='İptal eden')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='İptal sebebi')),
                ('customer_note', models.CharField(blank=True, max_length=200, verbose_name='Müşteri notu')),
                ('shop_note', models.CharField(blank=True, max_length=200, verbose_name='Dükkan notu')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Durum değişikliği')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='shops.service', verbose_name='Hizmet')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='shops.shop', verbose_name='Dükkan')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['shop', 'date'], name='appt_shop_date_idx'), models.Index(fields=['customer', 'status', 'date'], name='appt_customer_status_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('shop', 'date', 'start_time'), name='uniq_active_slot')],
            },
        ),
    ]
